#lang racket
(require "mk.rkt")
(print-as-expression #f)
 
(define apply-Go
  (lambda (G e t)
    (fresh (a G^)
           (== `(,a . ,G^) G)
           (fresh (aa da)
                  (== `(,aa . ,da) a)
                  (conde
                   ((== aa e) (== da t))
                   ((=/= aa e) (apply-Go G^ e t)))))))

(define !-
  (lambda (G e t) 
    (conde
     ((numbero e) (== 'Nat t))
     ((== t 'Bool)
      (conde
       ((== #t e))
       ((== #f e))))
     ((fresh (lhs rhs)
             (== `(cons ,lhs ,rhs) e)
             (fresh (t1 t2)
                    (== `(pairof ,t1 ,t2) t)
                    (!- G lhs t1) 
                    (!- G rhs t2))))   
     ((fresh (x)
             (== `(car ,x) e)
             (fresh (t1)
                    (== 'Nat t) 
                    (!- G x `(pairof Nat ,t1)))))
     ((fresh (x)
             (== `(cdr ,x) e)
             (fresh (t1)
                    (== 'Nat t) 
                    (!- G x `(pairof ,t1 Nat)))))     
     ((fresh (v)
             (== `(car ,v) e)
             (== t 'Bool)
             (!- G v t)))
     ((fresh (v)
             (== `(not ,v) e)
             (== t 'Bool)
             (!- G v t)))
     ((fresh (n)
             (== `(zero? ,n) e)
             (== t 'Bool)
             (!- G n 'Nat)))
     ((fresh (n)
             (== `(sub1 ,n) e)
             (== t 'Nat)
             (!- G n 'Nat)))
     ((fresh (ne1 ne2) 
             (== `(+ ,ne1 ,ne2) e)
             (== 'Nat t)
             (!- G ne1 'Nat)
             (!- G ne2 'Nat)))
     ((fresh (ne1 ne2)
             (== `(* ,ne1 ,ne2) e)
             (== 'Nat t)
             (!- G ne1 'Nat)
             (!- G ne2 'Nat)))
     ((fresh (teste anse elsee)
             (== `(if ,teste ,anse ,elsee) e)
             (!- G teste 'Bool)
             (!- G anse t)
             (!- G elsee t)))
     ((symbolo e) (apply-Go G e t))
     ((fresh (x b)
             (== `(lambda (,x) ,b) e)
             (symbolo x)
             (fresh (tx tb)          
                    (== `(,tx -> ,tb) t)
                    (!- `((,x . ,tx) . ,G) b tb))))
     ((fresh (x b)
             (== `(fix (lambda (,x) ,b)) e)
             (symbolo x)
             (fresh (t1)          
                    (== t1 t)
                    (!- `((,x . ,t1) . ,G) b t1))))
     ((fresh (e1 arg)
             (== `(,e1 ,arg) e)
             (fresh (targ)
                    (!- G e1 `(,targ -> ,t))
                    (!- G arg targ)))))))
     
   

